//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phanmemquanlybanhang.Model
{
    using Phanmemquanlybanhang.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue:BaseViewModel
    {
        private int _Id { get; set; }
        public int Id { get => _Id;set { _Id = value; OnPropertyChanged(); } }
        Nullable<System.DateTime> _Date { get; set; }
        public Nullable<System.DateTime> Date { get=>_Date; set { _Date = value;OnPropertyChanged(); } }
        private Decimal _TotalRevenue {  get; set; }
        public Decimal TotalRevenue { get => _TotalRevenue; set { _TotalRevenue = value; OnPropertyChanged(); } }
        public Nullable<int> StaffId { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
